- hosts: all
  remote_user: gosik
  gather_facts: no
  become: yes
  vars:
    zeus_db_password: "{{ (lookup('file', 'secrets/zeus-secrets-{{ inventory_hostname }}.json') | from_json)['db_password'] }}"
  tasks:

    - name: zeus user
      user:
        name: zeus
        shell: /bin/bash
        home: /srv/zeus/

    - name: www-data user
      user:
        name: www-data
        groups: zeus
        append: yes

    - name: config dir
      file:
        path: /srv/zeus/config
        state: directory
        owner: zeus
        group: zeus

    - name: secrets.json
      copy:
        src: 'secrets/zeus-secrets-{{ inventory_hostname }}.json'
        dest: /srv/zeus/config/secrets.json
        owner: zeus
        group: zeus
        mode: 0770

    - name: settings_local.py
      template:
        src: templates/zeus_settings_local.py
        dest: /srv/zeus/config/settings_local.py
        owner: zeus
        group: zeus
        mode: 0770

    - name: uwsgi.ini
      template:
        src: templates/zeus_uwsgi.ini
        dest: /srv/zeus/uwsgi.ini
        owner: zeus

    - name: /var/run/zeus
      file:
        path: /var/run/zeus
        state: directory
        owner: zeus
        group: zeus
        mode: 0770

    - name: uwsgi service configuration
      template:
        src: templates/zeus-uwsgi.service
        dest: /etc/systemd/system/zeus-uwsgi.service
      notify: systemctl daemon-reload

    - name: worker service configuration
      template:
        src: templates/zeus-worker.service
        dest: /etc/systemd/system/zeus-worker.service
      notify: systemctl daemon-reload

    - name: make initial virtualenv
      pip:
        name: "{{ item }}"
        state: latest
        virtualenv: /srv/zeus/virtualenv
        virtualenv_python: python3.6
      become_user: zeus
      with_items:
        - pipenv
        - uwsgi

    - name: check git repo
      git:
        repo: "{{ zeus_git_repo }}"
        dest: /srv/zeus/install
        version: "{{ zeus_git_version }}"
      become_user: zeus
      register: git_repo
      tags: [deploy]
      check_mode: yes

    - name: check version file
      copy:
        dest: /srv/zeus/version
        content: "{{ git_repo.after }}"
        owner: zeus
        group: zeus
      register: version_file
      check_mode: yes

    - name: deploy new version
      tags: [deploy]
      when: version_file.changed
      block:

      - name: remove version file
        file:
          path: /srv/zeus/version
          state: absent

      - name: stop services
        service: name="{{ item }}" state=stopped
        with_items:
          - zeus-uwsgi
          - zeus-worker

      - name: update source
        git:
          repo: "{{ zeus_git_repo }}"
          dest: /srv/zeus/install
          version: "{{ git_repo.after }}"
          refspec: "refs/heads/{{ zeus_git_version }}"
        become_user: zeus

      - name: set permissions of data directories
        file:
          path: "/srv/zeus/install/{{ item }}"
          state: directory
          owner: zeus
          group: zeus
          mode: 0770
        with_items:
          - data
          - data/election_logs
          - data/mixes
          - data/proofs
          - data/results

      - name: symlink settings/local.py
        file:
          src: /srv/zeus/config/settings_local.py
          dest: /srv/zeus/install/settings/local.py
          state: link
          owner: zeus
          group: zeus

      - name: pipenv sync
        shell: |
          . ../virtualenv/bin/activate
          pipenv sync
        args:
          chdir: /srv/zeus/install
        become_user: zeus

      - name: compile translations
        shell: |
          . ../virtualenv/bin/activate
          ./compile-translations.sh
        args:
          chdir: /srv/zeus/install
        become_user: zeus

      - name: update static files
        shell: |
          . ../virtualenv/bin/activate
          rm -rf sitestatic
          python manage.py collectstatic --noinput
        args:
          chdir: /srv/zeus/install
        become_user: zeus

      - name: start services
        service: name="{{ item }}" state=started
        with_items:
          - zeus-uwsgi
          - zeus-worker

      - name: create version file
        copy:
          dest: /srv/zeus/version
          content: "{{ git_repo.after }}"
          owner: zeus
          group: zeus

  handlers:
    - name: systemctl daemon-reload
      command: systemctl daemon-reload
